services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    volumes:
      - ./readarr/data:/config
      - ./readarr/books:/books
      - ./scraper/certs/bookinfo-club.crt:/etc/ssl/certs/bookinfo-club.crt # Trust signed bookinfo cert
    ports:
      - 4000:8787
    restart: unless-stopped
  readarr-metadata-scraper:
    build: scraper
    container_name: readarr-metadata-scraper
    volumes:
      - ./cache:/opt/app/cache
    environment:
      - CACHE_ENABLED=true
      - CACHE_TTL=86400000 # 24h in milliseconds
    depends_on:
      - readarr
    networks:
      default:
        aliases:
          - api.bookinfo.club