FROM node:18-alpine
WORKDIR /opt/app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
EXPOSE 80 443
ENV NODE_ENV=development
ENV CACHE_DIR=/opt/app/cache
CMD ["pnpm", "start"]